# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  symlinks:
    security_baseline: "#{source_dir}"
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "6.0.0"
    concat:
      repo: "puppetlabs/concat"
      ref: "6.1.0"
    kmod:
      repo: "camptocamp/kmod"
      ref: "2.3.1"
    augeas:
      repo: "camptocamp/augeas"
      ref: "1.8.0"
    sysctl:
      repo: "herculesteam/augeasproviders_sysctl"
      ref: "2.3.1"
    augeasproviders:
      repo: "herculesteam/augeasproviders"
      ref: "2.2.1"
    augeasprovider_core:
      repo: "herculesteam/augeasproviders_core"
      ref: "2.4.0"
    augeasprovider_pam:
      repo: "herculesteam/augeasproviders_pam"
      ref: "2.2.1"
    augeasprovider_grub:
      repo: "herculesteam/augeasproviders_grub"
      ref: "3.1.0"
    autofs:
      repo: "puppet/autofs"
      ref: "5.0.1"
    echo:
      repo: "ipcrm/echo"
      ref: "0.1.6"
    syslogng:
      repo: "purplehazech/syslogng"
      ref: "0.7.1"
    rsyslog:
      repo: "puppet/rsyslog"
      ref: "3.3.0"
    logrotate:
      repo: "puppet/logrotate"
      ref: "4.0.0"
    ntp:
      repo: "puppetlabs/ntp"
      ref: "8.0.0"
    chrony:
      repo: "jorten/chrony"
      ref: "0.3.0"
    augeas_core:
      repo: "puppetlabs/augeas_core"
      ref: "1.0.5"
